const brochureRequestTemplate = (name, email, purpose) => {
  return `
    <div style="font-family: Arial, sans-serif; padding: 20px; background: #f4f4f4;">
      <div style="max-width:600px; margin:auto; background:#fff; padding:20px; border-radius:8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
        <h2 style="color:#007bff; border-bottom: 2px solid #eee; padding-bottom: 10px;">
          📩 New Brochure Request
        </h2>

        <p style="font-size: 16px;"><strong>Name:</strong> ${name}</p>
        <p style="font-size: 16px;"><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>

        <p style="font-size: 16px;"><strong>Purpose:</strong></p>
        <blockquote style="border-left:4px solid #007bff; padding-left:15px; color: #555; font-style: italic; background: #f9f9f9; padding: 10px;">
          ${purpose}
        </blockquote>

        <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
        <p style="font-size:12px; color:#999; text-align: center;">
          🚀 Automatically generated by Core Talents Backend
        </p>
      </div>
    </div>
  `;
};

module.exports = { brochureRequestTemplate };
